Replace `setup.py`s with `pyproject.toml`s (#2317)

diff --git a/scripts/pypi_publish b/scripts/pypi_publish
--- a/scripts/pypi_publish
+++ b/scripts/pypi_publish
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+set -euo pipefail
+
 # Determine the script's directory (even if it's a symbolic link)
 SOURCE="${BASH_SOURCE[0]}"
 while [ -h "$SOURCE" ]; do SOURCE="$(readlink "$SOURCE")"; done
@@ -7,7 +9,16 @@ SCRIPTS_DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
 SRC_DIR="$(cd -P "$(dirname "$SCRIPTS_DIR")" && pwd)"
 
 # List of plugins to publish
-plugins=("rastervision_pipeline" "rastervision_aws_batch" "rastervision_aws_s3" "rastervision_core" "rastervision_pytorch_learner" "rastervision_pytorch_backend" "rastervision_gdal_vsi" "rastervision_aws_sagemaker")
+plugins=(
+    "rastervision_pipeline"
+    "rastervision_aws_batch"
+    "rastervision_aws_s3"
+    "rastervision_core"
+    "rastervision_pytorch_learner"
+    "rastervision_pytorch_backend"
+    "rastervision_gdal_vsi"
+    "rastervision_aws_sagemaker"
+)
 
 # Usage documentation
 function usage() {
@@ -34,11 +45,11 @@ function publish_package() {
 
 # publish a plugin
 function publish_plugin() {
+    pushd "$SRC_DIR/$1" >/dev/null
     local plugin_name="$1"
-    cd "$SRC_DIR/$plugin_name"
     echo "Publishing $plugin_name ... "
     publish_package
-    cd "$SRC_DIR"
+    popd >/dev/null
 }
 
 # publish all plugins and the top-level package
@@ -49,19 +60,21 @@ function publish_all() {
     done
 
     # Publish the top-level package
+    pushd "$SRC_DIR" >/dev/null
     echo "Publishing rastervision ... "
     publish_package
+    popd >/dev/null
 }
 
 # Check for command-line arguments
-if [[ "$1" == "--help" || "$1" == "-h" ]]; then
+if [[ ${1:-} == "--help" || ${1:-} == "-h" ]]; then
     usage
     exit
 fi
 
 # Check if the --test flag is passed
 publish_to_test=false
-if [[ "$1" == "--test" ]]; then
+if [[ ${1:-} == "--test" ]]; then
     publish_to_test=true
     # Remove the --test flag from the arguments
     shift
@@ -74,19 +87,18 @@ if [ "$publish_to_test" = true ]; then
 fi
 
 # If actually publishing: prompt for confirmation
-if [[ "$1" == "-y" ]]; then
+if [[ ${1:-} == "-y" ]]; then
     response="y"
 else
     read -r -p "Actually publish to PyPI? (y/N): " response
 fi
 
 case "$response" in
-    [yY][eE][sS]|[yY])
-        echo "Publishing to PyPI..."
-        publish_all
-        ;;
-    *)
-        echo "Aborting."
-        ;;
+[yY][eE][sS] | [yY])
+    echo "Publishing to PyPI..."
+    publish_all
+    ;;
+*)
+    echo "Aborting."
+    ;;
 esac
-
